# Generated by Django 4.1.4 on 2023-02-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
